import hmac
import os
import secrets
import glob
from fastapi import FastAPI, Depends, Request, Response, Query, Body, HTTPException, UploadFile, File
from fastapi.responses import JSONResponse
from typing import Optional, List
from sqlalchemy.orm import Session
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from starlette.middleware.base import BaseHTTPMiddleware

from app.config   import settings
from app.database import Base, engine, get_db
from app.deps import get_current_user, require_superadmin

# Import all models so Alembic sees them
from app.models import *  # noqa

# Create tables (dev/test only — production MUST use Alembic migrations)
if settings.AUTO_CREATE_TABLES:
    Base.metadata.create_all(bind=engine)

# Create upload directory
os.makedirs(f"{settings.UPLOAD_DIR}/artwork", exist_ok=True)

app = FastAPI(
    title=settings.APP_NAME,
    version=settings.APP_VERSION,
    docs_url="/api/docs",
    redoc_url="/api/redoc",
)

# ── Read-Only Middleware ───────────────────────────────────────────────────────
# This is the authoritative write-block enforcement.
# It runs before any route handler, so even if a frontend bug fires a write
# request, the server rejects it with 403.

WRITE_METHODS = {"POST", "PUT", "PATCH", "DELETE"}

# These paths are whitelisted and may always accept writes.
# Only auth plumbing endpoints belong here — nothing else.
WRITE_WHITELIST = {
    "/api/v1/auth/login",
    "/api/v1/auth/logout",
    "/api/v1/auth/refresh",
    "/api/v1/auth/switch-company",
    "/api/v1/inter-company/link",
    "/api/v1/wholesale-sync",      # Push-only; token-auth, no JWT
}

class ReadOnlyMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        # Only inspect write methods
        if request.method not in WRITE_METHODS:
            return await call_next(request)

        # Whitelisted paths always pass through
        if request.url.path in WRITE_WHITELIST:
            return await call_next(request)

        # Try to decode the JWT
        auth_header = request.headers.get("Authorization", "")
        if not auth_header.startswith("Bearer "):
            # No token — let the route handle 401
            return await call_next(request)

        token = auth_header[len("Bearer "):]
        try:
            from jose import jwt as jose_jwt, JWTError
            payload = jose_jwt.decode(
                token,
                settings.SECRET_KEY,
                algorithms=[settings.ALGORITHM],
            )
        except Exception:
            # Invalid token — let the route handle 401
            return await call_next(request)

        legacy_cid = payload.get("company_id")
        home_cid   = payload.get("home_company_id",   legacy_cid)
        active_cid = payload.get("active_company_id", legacy_cid)

        role = payload.get("role", "")

        # Determine read-only status
        if home_cid is None or active_cid is None:
            is_read_only = False
        elif home_cid == active_cid:
            is_read_only = False
        elif request.url.path.rstrip("/").startswith("/api/v1/users") and role == "superadmin":
            # Superadmin administering users across companies is permitted
            is_read_only = False
        else:
            if settings.ALLOW_SUPERADMIN_CROSS_EDIT and role == "superadmin":
                is_read_only = False
            else:
                is_read_only = True

        if is_read_only:
            # Fetch company name for a helpful error message
            company_name = "another company"
            try:
                from app.database import SessionLocal
                from app.models.company import Company as CompanyModel
                db = SessionLocal()
                try:
                    c = db.query(CompanyModel).filter(
                        CompanyModel.id == active_cid
                    ).first()
                    if c:
                        company_name = c.name
                finally:
                    db.close()
            except Exception:
                pass

            return JSONResponse(
                status_code=403,
                content={
                    "detail": (
                        f"Read-only mode: you are viewing {company_name}. "
                        f"Log in to this company to make changes."
                    )
                },
            )

        return await call_next(request)


app.add_middleware(ReadOnlyMiddleware)

# ── CORS ──────────────────────────────────────────────────────────────────────
# Added after ReadOnlyMiddleware so CORSMiddleware is registered last (outermost).
# This ensures 403 responses generated by ReadOnlyMiddleware include CORS headers.
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.origins_list,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Serve uploads ──────────────────────────────────────────────────────────────
app.mount("/uploads", StaticFiles(directory="uploads"), name="uploads")

# ── Import and register routers ───────────────────────────────────────────────
from app.routers.auth import router as auth_router
from app.routers      import make_crud_router
from app.models.customer       import Customer
from app.models.vendor         import Vendor
from app.models.product        import Product
from app.models.employee       import Employee
from app.models.crm            import CRMStage, CRMLead
from app.models.quotation      import Quotation
from app.models.sales_order    import SalesOrder
from app.models.purchase_order import PurchaseOrder
from app.models.delivery       import DeliveryChallan
from app.models.invoice        import Invoice
from app.models.inventory      import StockMovement
from app.models.workshop       import WorkshopOrder, TougheningBatch
from app.models.user           import User
from app.models.company        import Company
from app.models.process_master import ProcessMaster
from app.models.warehouse      import Warehouse
from app.models.company_settings import CompanySetting
from app.models.payment import Payment
from app.models.payment_allocation import PaymentAllocation

from app.routers.auth import router as auth_router
from app.routers.settings import router as settings_router
from app.routers.super import router as super_router
from app.routers.reports import router as reports_router
from app.routers.inter_company import router as inter_company_router
from app.routers.payments import router as payments_router
from app.routers.delivery_notes import router as delivery_notes_router

PREFIX = "/api/v1"

# Auth
app.include_router(auth_router, prefix=f"{PREFIX}")

# Settings
app.include_router(settings_router)

# SuperAdmin
app.include_router(super_router, prefix=f"{PREFIX}")

# Reports
app.include_router(reports_router)

# Inter-Company
app.include_router(inter_company_router, prefix=f"{PREFIX}")

# Payments (dedicated router with allocation support — replaces generic CRUD)
app.include_router(payments_router)

# Delivery Notes
app.include_router(delivery_notes_router, prefix=f"{PREFIX}")


# Auto CRUD routers
ROUTER_CONFIGS = [
    {"prefix": "/companies",       "tag": "Companies",       "model": Company,         "code_prefix": "COMP", "code_field": None, "company_scoped": True, "read_roles": None, "write_roles": {"superadmin"}, "module": "company"},
    {"prefix": "/customers",       "tag": "Customers",       "model": Customer,        "code_prefix": "CUST", "code_field": "customer_code", "module": "customers"},
    {"prefix": "/vendors",         "tag": "Vendors",         "model": Vendor,          "code_prefix": "VEND", "code_field": "vendor_code", "module": "vendors"},
    {"prefix": "/products",        "tag": "Products",        "model": Product,         "code_prefix": "PROD", "code_field": "internal_ref", "module": "products"},
    {"prefix": "/employees",       "tag": "Employees",       "model": Employee,        "code_prefix": "EMP",  "code_field": "employee_code", "module": "employees"},
    {"prefix": "/crm/stages",      "tag": "CRM Stages",      "model": CRMStage,        "code_prefix": None,   "code_field": None, "module": "stages"},
    {"prefix": "/crm/leads",       "tag": "CRM Leads",       "model": CRMLead,         "code_prefix": "OPP",  "code_field": "lead_number", "module": "leads"},
    {"prefix": "/quotations",      "tag": "Quotations",      "model": Quotation,       "code_prefix": "QT",   "code_field": "quote_number", "module": "quotations"},
    {"prefix": "/sales-orders",    "tag": "Sales Orders",    "model": SalesOrder,      "code_prefix": "SO",   "code_field": "so_number", "module": "sales_orders"},
    {"prefix": "/purchase-orders", "tag": "PO",              "model": PurchaseOrder,   "code_prefix": "PO",   "code_field": "po_number", "module": "purchase_orders"},
    {"prefix": "/delivery",        "tag": "Delivery",        "model": DeliveryChallan, "code_prefix": "DC",   "code_field": "dc_number", "module": "delivery_challans"},
    {"prefix": "/invoices",        "tag": "Invoices",        "model": Invoice,         "code_prefix": "INV",  "code_field": "invoice_number", "module": "invoices"},
    {"prefix": "/inventory",       "tag": "Inventory",       "model": StockMovement,   "code_prefix": "SM",   "code_field": "move_number", "module": "stock_movements"},
    {"prefix": "/workshop",        "tag": "Workshop",        "model": WorkshopOrder,   "code_prefix": "WO",   "code_field": "wo_number", "module": "workshop_orders"},
    {"prefix": "/toughening",      "tag": "Toughening",      "model": TougheningBatch, "code_prefix": "TB",   "code_field": "tb_number", "module": "toughening"},
    # NOTE: Process Masters are intentionally a shared global catalogue across all companies
    {"prefix": "/process-masters", "tag": "Process Masters", "model": ProcessMaster,  "code_prefix": None,   "code_field": None, "company_scoped": False, "module": "process_masters"},
    {"prefix": "/warehouses",      "tag": "Warehouses",      "model": Warehouse,      "code_prefix": None,   "code_field": None, "module": "stock"},
    {"prefix": "/users",           "tag": "Users",           "model": User,            "code_prefix": None,   "code_field": None, "read_roles": {"admin", "superadmin"}, "write_roles": {"superadmin"}},
    # Payments removed — handled by dedicated router with allocation support
]

from pydantic import BaseModel
class DynCreate(BaseModel):
    model_config = {"extra": "allow"}
class DynUpdate(BaseModel):
    model_config = {"extra": "allow"}

# ── Force Logout Endpoint (superadmin only) ───────────────────────────────────
@app.post("/api/v1/users/{user_id}/force-logout")
def force_logout_user(
    user_id: int,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_superadmin),
):
    target_user = db.query(User).filter(User.id == user_id).first()
    if not target_user:
        raise HTTPException(status_code=404, detail="User not found")
    target_user.current_session_id = None
    target_user.session_started_at = None
    db.commit()
    return {"ok": True}

# ── Specific Workshop endpoints (MUST be defined before generic CRUD /{item_id} router) ──
@app.get("/api/v1/workshop/cutting-register")
def get_cutting_register(
    target_date: Optional[str] = Query(None, alias="date"),
    preset: Optional[str] = Query("today"),
    db: Session = Depends(get_db),
    user = Depends(get_current_user),
):
    """Pre-aggregated Daily Cutting Register for Dashboard."""
    import re
    from datetime import datetime, date, timedelta
    from app.models.workshop import WorkshopOrder
    from app.models.product import Product
    from app.utils.helpers import apply_company_filter, apply_scope_filter

    today_d = date.today()
    if target_date:
        try:
            parsed_d = datetime.strptime(target_date, "%Y-%m-%d").date()
        except ValueError:
            parsed_d = today_d
    else:
        parsed_d = today_d

    if preset == "yesterday":
        start_d = today_d - timedelta(days=1)
        end_d = today_d - timedelta(days=1)
    elif preset == "this_week":
        start_d = today_d - timedelta(days=today_d.weekday())
        end_d = today_d
    else:
        start_d = parsed_d
        end_d = parsed_d

    query = db.query(WorkshopOrder).filter(WorkshopOrder.is_active == True)
    query = apply_company_filter(query, WorkshopOrder, user.active_company_id)
    query = apply_scope_filter(query, WorkshopOrder, user, "workshop_orders")
    wos = query.order_by(WorkshopOrder.id.desc()).all()

    # Pre-cache product thickness map
    product_thick_map = {}
    products = db.query(Product).filter(Product.is_active == True).all()
    for p in products:
        if getattr(p, "thickness", None) is not None:
            try:
                product_thick_map[p.id] = float(p.thickness)
            except (ValueError, TypeError):
                pass

    def parse_thickness(line):
        thick = line.get("thickness") if line.get("thickness") is not None else line.get("glass_thickness")
        if isinstance(thick, (int, float)):
            return float(thick)
        if isinstance(thick, str):
            try:
                return float(thick)
            except ValueError:
                pass
        prod_thick = line.get("product_thickness")
        if isinstance(prod_thick, (int, float)):
            return float(prod_thick)
        if isinstance(prod_thick, str):
            try:
                return float(prod_thick)
            except ValueError:
                pass

        pid = line.get("product_id")
        if pid and pid in product_thick_map:
            return product_thick_map[pid]

        desc = str(line.get("description") or "")
        match = re.search(r'(\d+(?:\.\d+)?)\s*mm', desc, re.IGNORECASE)
        if match:
            try:
                return float(match.group(1))
            except ValueError:
                pass
        return None

    def classify_glass(thickness):
        if thickness is None:
            return "unclassified"
        if thickness < 8:
            return "thin"
        return "thick"

    def calc_line_sqft(line):
        chg_w = line.get("chg_w_in") or line.get("charged_w") or line.get("charged_w_in") or line.get("charged_w_inch") or line.get("ceiling_w_inches")
        chg_h = line.get("chg_h_in") or line.get("charged_h") or line.get("charged_h_in") or line.get("charged_h_inch") or line.get("ceiling_h_inches")

        if chg_w is None and line.get("charged_w_mm"):
            chg_w = line.get("charged_w_mm") / 25.4
        if chg_h is None and line.get("charged_h_mm"):
            chg_h = line.get("charged_h_mm") / 25.4

        is_charged = True
        if chg_w is None or chg_h is None:
            is_charged = False
            act_w = line.get("act_w_in") or line.get("width_inch") or line.get("width_in")
            act_h = line.get("act_h_in") or line.get("height_inch") or line.get("height_in")
            if act_w is None and line.get("width_mm"):
                act_w = line.get("width_mm") / 25.4
            if act_h is None and line.get("height_mm"):
                act_h = line.get("height_mm") / 25.4
            w, h = act_w or 0, act_h or 0
        else:
            w, h = chg_w, chg_h

        qty = line.get("qty") or line.get("quantity") or 1
        try:
            w, h, qty = float(w), float(h), float(qty)
        except (ValueError, TypeError):
            w, h, qty = 0, 0, 1

        sqft = (w * h * qty) / 144.0
        return sqft, is_charged

    status_map = {
        "draft": "PENDING",
        "in_progress": "UNDR CTNG",
        "completed": "RDY",
        "cancelled": "CANCELLED",
    }

    tile_data = {
        "cut_today": {"thin": 0.0, "thick": 0.0, "unclassified": 0.0},
        "in_progress": {"thin": 0.0, "thick": 0.0, "unclassified": 0.0},
        "pending": {"thin": 0.0, "thick": 0.0, "unclassified": 0.0},
        "completed": {"thin": 0.0, "thick": 0.0, "unclassified": 0.0},
    }

    rows = []
    fallback_line_count = 0

    for wo in wos:
        thin_sqft = 0.0
        thick_sqft = 0.0
        unclassified_sqft = 0.0

        wo_cut_pieces = 0
        wo_total_pieces = 0
        lines = wo.lines or []
        wo_completed = (wo.status == "completed")

        for line in lines:
            if not isinstance(line, dict):
                continue

            # J5 Hydration on missing qty_cut
            if line.get("qty_cut") is None:
                if wo_completed:
                    line["qty_cut"] = line.get("qty") or line.get("quantity") or 1
                    comp_dt = wo.updated_at or wo.created_at or datetime.utcnow()
                    line["cut_completed_at"] = comp_dt.isoformat() if hasattr(comp_dt, "isoformat") else str(comp_dt)
                else:
                    line["qty_cut"] = 0

            thick_val = parse_thickness(line)
            sqft, is_charged = calc_line_sqft(line)
            if not is_charged:
                fallback_line_count += 1

            cat = classify_glass(thick_val)
            if cat == "thin":
                thin_sqft += sqft
            elif cat == "thick":
                thick_sqft += sqft
            else:
                unclassified_sqft += sqft

            qty = float(line.get("qty") or line.get("quantity") or 1)
            qty_cut = float(line.get("qty_cut") or 0)
            unit_sqft = (sqft / qty) if qty > 0 else 0.0
            qty_pending = max(0.0, qty - qty_cut)

            wo_cut_pieces += int(qty_cut)
            wo_total_pieces += int(qty)

            # Tiles categorization
            # 1. Completed cumulative
            if qty > 0 and qty_cut >= qty:
                tile_data["completed"][cat] += unit_sqft * qty_cut
            # 2. Cut Today (if completion timestamp matches date range)
            comp_at = line.get("cut_completed_at")
            if comp_at:
                try:
                    c_date = datetime.fromisoformat(str(comp_at).replace("Z", "+00:00")).date()
                    if start_d <= c_date <= end_d:
                        tile_data["cut_today"][cat] += unit_sqft * qty_cut
                except Exception:
                    pass

            # 3. In Progress
            cut_started = line.get("cut_started_at")
            if (cut_started or qty_cut > 0) and qty_cut < qty:
                tile_data["in_progress"][cat] += unit_sqft * qty_pending
            # 4. Pending
            if not cut_started and qty_cut == 0:
                tile_data["pending"][cat] += unit_sqft * qty

        row_total = thin_sqft + thick_sqft + unclassified_sqft
        if lines:
            descs = [l.get("description") for l in lines if isinstance(l, dict) and l.get("description")]
            date_str = wo.order_date
            if not date_str and wo.created_at:
                date_str = wo.created_at.strftime("%Y-%m-%d")

            pct = round((wo_cut_pieces / wo_total_pieces * 100), 1) if wo_total_pieces > 0 else 0.0

            rows.append({
                "key": wo.id,
                "id": wo.id,
                "date": date_str or "—",
                "wo_number": wo.wo_number or f"WO-{wo.id}",
                "customer_name": wo.customer_name or "—",
                "description": ", ".join(descs) if descs else "—",
                "thin_sqft": round(thin_sqft, 2) if thin_sqft > 0 else None,
                "thick_sqft": round(thick_sqft, 2) if thick_sqft > 0 else None,
                "unclassified_sqft": round(unclassified_sqft, 2) if unclassified_sqft > 0 else None,
                "total_sqft": round(row_total, 2),
                "cut_pieces": wo_cut_pieces,
                "total_pieces": wo_total_pieces,
                "progress_pct": pct,
                "status": wo.status or "draft",
                "status_label": status_map.get(wo.status, "PENDING"),
            })

    fmt_tile = lambda t: {
        "thin_sqft": round(t["thin"], 2),
        "thick_sqft": round(t["thick"], 2),
        "unclassified_sqft": round(t["unclassified"], 2),
        "total_sqft": round(t["thin"] + t["thick"] + t["unclassified"], 2),
    }

    cut_today_res = fmt_tile(tile_data["cut_today"])
    in_prog_res = fmt_tile(tile_data["in_progress"])
    pending_res = fmt_tile(tile_data["pending"])
    completed_res = fmt_tile(tile_data["completed"])

    return {
        "items": rows,
        "cut_today": cut_today_res,
        "in_progress": in_prog_res,
        "pending": pending_res,
        "completed": completed_res,
        # Backward compatibility aliases
        "total_thin_sqft": cut_today_res["thin_sqft"],
        "total_thick_sqft": cut_today_res["thick_sqft"],
        "total_unclassified_sqft": cut_today_res["unclassified_sqft"],
        "total_all_sqft": cut_today_res["total_sqft"],
        "fallback_line_count": fallback_line_count,
        "selected_date": start_d.strftime("%Y-%m-%d"),
        "preset": preset,
    }


@app.get("/api/v1/workshop/by-so/{so_id}")
def get_wo_by_so(
    so_id: int,
    db: Session = Depends(get_db),
    user = Depends(get_current_user),
):
    """Get all Workshop Orders linked to a Sales Order (scoped to active company)."""
    from app.models.sales_order import SalesOrder
    from app.models.workshop import WorkshopOrder

    so = db.query(SalesOrder).filter(SalesOrder.id == so_id).first()
    if not so:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail="Sales Order not found")
    if (
        user.active_company_id is not None
        and so.company_id is not None
        and so.company_id != user.active_company_id
    ):
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail="Sales Order not found")

    wos = db.query(WorkshopOrder).filter(
        WorkshopOrder.so_id == so_id,
    ).all()
    return {
        "items": [
            {
                "id": wo.id,
                "wo_number": wo.wo_number,
                "status": wo.status,
                "order_date": wo.order_date,
                "customer_name": wo.customer_name,
                "lines_count": len(wo.lines or []),
            }
        ],
        "total": len(wos),
    }


@app.post("/api/v1/workshop/{wo_id}/share-file")
async def upload_wo_file(
    wo_id: int,
    file: UploadFile = File(...),
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    if not file.filename.endswith(".xlsx"):
        raise HTTPException(status_code=400, detail="Only .xlsx files are allowed")

    contents = await file.read()
    if len(contents) > 5 * 1024 * 1024:
        raise HTTPException(status_code=400, detail="File size exceeds 5 MB limit")

    wo_dir = os.path.join(settings.UPLOAD_DIR, "wo")
    os.makedirs(wo_dir, exist_ok=True)

    # Delete existing file for this wo_id to prevent accumulation
    existing_pattern = os.path.join(wo_dir, f"WO{wo_id}_*.xlsx")
    for old_file in glob.glob(existing_pattern):
        try:
            os.remove(old_file)
        except Exception:
            pass

    token = secrets.token_urlsafe(8)
    filename = f"WO{wo_id}_{token}.xlsx"
    filepath = os.path.join(wo_dir, filename)

    with open(filepath, "wb") as f:
        f.write(contents)

    return {"url": f"/uploads/wo/{filename}"}


for cfg in ROUTER_CONFIGS:
    r = make_crud_router(
        prefix=f"{PREFIX}{cfg['prefix']}",
        tag=cfg["tag"],
        model=cfg["model"],
        create_schema=DynCreate,
        update_schema=DynUpdate,
        response_schema=DynCreate,
        code_prefix=cfg.get("code_prefix"),
        code_field=cfg.get("code_field"),
        company_scoped=cfg.get("company_scoped", True),
        read_roles=cfg.get("read_roles"),
        write_roles=cfg.get("write_roles"),
        module=cfg.get("module"),
    )
    app.include_router(r)


# ── Receivables Summary (dashboard numbers) ───────────────────────────────────
# Phase 2A: Rewritten to use Invoice-based accounting with allocations.
# Sales Orders leave AR entirely.
@app.get("/api/v1/receivables/summary")
def receivables_summary(
    db: Session = Depends(get_db),
    user = Depends(get_current_user),
):
    from app.models.invoice import Invoice
    from app.models.payment import Payment
    from app.models.payment_allocation import PaymentAllocation
    from sqlalchemy import func
    from app.utils.helpers import apply_company_filter, apply_scope_filter

    # Billed = Invoice.total_amount where status != 'cancelled' and is_active
    inv_q = db.query(Invoice)
    inv_q = apply_company_filter(inv_q, Invoice, user.active_company_id)
    inv_q = apply_scope_filter(inv_q, Invoice, user, "invoices")
    inv_q = inv_q.filter(Invoice.is_active == True, Invoice.status != "cancelled")

    total_billed = inv_q.with_entities(func.sum(Invoice.total_amount)).scalar() or 0

    # Received = sum(payment_allocations.amount) for active allocations on active payments
    alloc_q = (
        db.query(func.sum(PaymentAllocation.amount))
        .join(Payment, PaymentAllocation.payment_id == Payment.id)
        .filter(
            PaymentAllocation.is_active == True,
            Payment.is_active == True,
        )
    )
    alloc_q = apply_company_filter(alloc_q, PaymentAllocation, user.active_company_id)
    total_received = alloc_q.scalar() or 0

    outstanding = round(max(0, total_billed - total_received), 2)

    # On-account = total payments - total allocations
    pay_q = db.query(func.sum(Payment.amount)).filter(Payment.is_active == True)
    pay_q = apply_company_filter(pay_q, Payment, user.active_company_id)
    total_payments = pay_q.scalar() or 0

    on_account = round(max(0, total_payments - total_received), 2)

    eff_scope = getattr(user, "data_scope", "company")
    if isinstance(getattr(user, "module_scopes", None), dict):
        eff_scope = user.module_scopes.get("invoices", eff_scope)
    is_scoped = (user.role not in ("superadmin", "admin")) and (eff_scope == "own")

    return {
        "total_billed": round(total_billed, 2),
        "total_collected": round(total_received, 2),
        "outstanding": outstanding,
        "advance": on_account,  # renamed conceptually but key kept for compat
        "on_account": on_account,
        "is_scoped": is_scoped,
    }


# ── Customer Ledger ────────────────────────────────────────────────────────────
# Phase 2A: Transactions are now Invoices (not Sales Orders).
@app.get("/api/v1/receivables/customer/{customer_id}")
def customer_ledger(
    customer_id: int,
    db: Session = Depends(get_db),
    user = Depends(get_current_user),
):
    from app.models.invoice import Invoice
    from app.models.payment import Payment
    from app.models.payment_allocation import PaymentAllocation
    from app.models.customer import Customer
    from app.utils.helpers import apply_company_filter, apply_scope_filter
    from fastapi import HTTPException
    from sqlalchemy import func

    customer = db.query(Customer).filter(Customer.id == customer_id).first()
    if not customer:
        raise HTTPException(status_code=404, detail="Customer not found")

    # Verify customer belongs to active company
    if (
        user.active_company_id is not None
        and customer.company_id is not None
        and customer.company_id != user.active_company_id
    ):
        raise HTTPException(status_code=404, detail="Customer not found")

    # Invoices as debit entries
    inv_q = db.query(Invoice).filter(
        Invoice.customer_id == customer_id,
        Invoice.is_active == True,
        Invoice.status != "cancelled",
    )
    inv_q = apply_company_filter(inv_q, Invoice, user.active_company_id)
    inv_q = apply_scope_filter(inv_q, Invoice, user, "invoices")
    invoices = inv_q.order_by(Invoice.id.asc()).all()

    # Payments as credit entries
    pay_q = db.query(Payment).filter(
        Payment.customer_id == customer_id,
        Payment.is_active == True,
    )
    pay_q = apply_company_filter(pay_q, Payment, user.active_company_id)
    payments = pay_q.order_by(Payment.id.asc()).all()

    transactions = []

    for inv in invoices:
        transactions.append({
            "id": f"inv_{inv.id}",
            "date": inv.invoice_date or str(inv.created_at)[:10],
            "reference": inv.invoice_number,
            "type": "invoice",
            "description": f"Invoice {inv.invoice_number}",
            "debit": round(inv.total_amount or 0, 2),
            "credit": 0,
            "invoice_id": inv.id,
            "payment_id": None,
        })

    for pay in payments:
        # Get allocations for this payment to show which invoices it covers
        allocs = (
            db.query(PaymentAllocation)
            .filter(
                PaymentAllocation.payment_id == pay.id,
                PaymentAllocation.is_active == True,
            )
            .all()
        )
        alloc_details = [
            {"invoice_id": a.invoice_id, "amount": a.amount}
            for a in allocs
        ]

        transactions.append({
            "id": f"pay_{pay.id}",
            "date": pay.payment_date or str(pay.created_at)[:10],
            "reference": pay.payment_number,
            "type": "payment",
            "description": f"Payment via {pay.payment_mode}" + (f" ({pay.payment_account})" if pay.payment_account else ""),
            "debit": 0,
            "credit": round(pay.amount or 0, 2),
            "invoice_id": None,
            "payment_id": pay.id,
            "payment_mode": pay.payment_mode,
            "payment_account": pay.payment_account,
            "payment_reference": pay.payment_reference,
            "allocations": alloc_details,
        })

    transactions.sort(key=lambda x: x["date"])

    running_balance = 0
    for t in transactions:
        running_balance += t["debit"] - t["credit"]
        t["balance"] = round(running_balance, 2)

    total_billed = sum(t["debit"] for t in transactions)
    total_paid = sum(t["credit"] for t in transactions)
    balance = round(total_billed - total_paid, 2)

    # On-account credit
    total_allocated = (
        db.query(func.sum(PaymentAllocation.amount))
        .join(Payment, PaymentAllocation.payment_id == Payment.id)
        .filter(
            Payment.customer_id == customer_id,
            Payment.is_active == True,
            PaymentAllocation.is_active == True,
        )
        .scalar()
    ) or 0
    on_account = round(max(0, total_paid - total_allocated), 2)

    return {
        "customer": {
            "id": customer.id,
            "name": customer.name,
            "phone": customer.phone,
            "gstin": customer.gstin,
        },
        "transactions": transactions,
        "total_billed": round(total_billed, 2),
        "total_paid": round(total_paid, 2),
        "balance": balance,
        "on_account": on_account,
    }


# ── Receivables per customer (for dashboard table) ─────────────────────────────
# Phase 2A: Invoice-based, N+1 fixed with join.
@app.get("/api/v1/receivables/customers")
def receivables_by_customer(
    db: Session = Depends(get_db),
    user = Depends(get_current_user),
):
    from app.models.invoice import Invoice
    from app.models.payment import Payment
    from app.models.payment_allocation import PaymentAllocation
    from app.models.customer import Customer
    from app.utils.helpers import apply_company_filter, apply_scope_filter
    from sqlalchemy import func

    # Billed per customer from Invoices (not SOs)
    inv_q = db.query(
        Invoice.customer_id,
        func.sum(Invoice.total_amount).label("total_billed"),
        func.count(Invoice.id).label("invoice_count"),
    )
    inv_q = apply_company_filter(inv_q, Invoice, user.active_company_id)
    inv_q = apply_scope_filter(inv_q, Invoice, user, "invoices")
    inv_q = inv_q.filter(Invoice.is_active == True, Invoice.status != "cancelled")
    inv_by_customer = inv_q.group_by(Invoice.customer_id).all()

    # Allocations (received) per customer
    alloc_q = db.query(
        Payment.customer_id,
        func.sum(PaymentAllocation.amount).label("total_allocated"),
    ).join(
        PaymentAllocation, PaymentAllocation.payment_id == Payment.id
    ).filter(
        Payment.is_active == True,
        PaymentAllocation.is_active == True,
    )
    alloc_q = apply_company_filter(alloc_q, Payment, user.active_company_id)
    alloc_by_customer = alloc_q.group_by(Payment.customer_id).all()
    alloc_map = {row.customer_id: float(row.total_allocated or 0) for row in alloc_by_customer}

    # Total payments per customer (for on-account calc)
    pay_q = db.query(
        Payment.customer_id,
        func.sum(Payment.amount).label("total_paid"),
    ).filter(Payment.is_active == True)
    pay_q = apply_company_filter(pay_q, Payment, user.active_company_id)
    pay_by_customer = pay_q.group_by(Payment.customer_id).all()
    pay_map = {row.customer_id: float(row.total_paid or 0) for row in pay_by_customer}

    # Batch-load customer names (fix N+1)
    customer_ids = [row.customer_id for row in inv_by_customer if row.customer_id is not None]
    for cid in pay_map:
        if cid not in customer_ids:
            customer_ids.append(cid)

    customers_map = {}
    if customer_ids:
        custs = db.query(Customer).filter(Customer.id.in_(customer_ids)).all()
        customers_map = {c.id: c for c in custs}

    # Build result from invoice-side customers
    result_map = {}
    for row in inv_by_customer:
        cust = customers_map.get(row.customer_id)
        if not cust:
            continue
        total_billed = float(row.total_billed or 0)
        total_allocated = alloc_map.get(row.customer_id, 0)
        total_paid = pay_map.get(row.customer_id, 0)
        balance = round(total_billed - total_allocated, 2)
        on_account = round(max(0, total_paid - total_allocated), 2)

        result_map[row.customer_id] = {
            "customer_id": row.customer_id,
            "customer_name": cust.name,
            "customer_phone": cust.phone or "",
            "total_billed": round(total_billed, 2),
            "total_paid": round(total_paid, 2),
            "balance": balance,
            "on_account": on_account,
            "invoice_count": row.invoice_count,
            "status": "advance" if balance < 0 else ("settled" if balance == 0 else "pending"),
        }

    # Add customers who have payments but no invoices
    for cid, total_paid in pay_map.items():
        if cid in result_map:
            continue
        cust = customers_map.get(cid)
        if not cust:
            continue
        total_allocated = alloc_map.get(cid, 0)
        on_account = round(max(0, total_paid - total_allocated), 2)
        result_map[cid] = {
            "customer_id": cid,
            "customer_name": cust.name,
            "customer_phone": cust.phone or "",
            "total_billed": 0,
            "total_paid": round(total_paid, 2),
            "balance": round(-total_paid, 2),
            "on_account": on_account,
            "invoice_count": 0,
            "status": "advance",
        }

    result = list(result_map.values())
    result.sort(key=lambda x: abs(x["balance"]), reverse=True)
    return {"items": result, "total": len(result)}


# ─── INVENTORY RECOMPUTATION & OPENING BALANCE ENDPOINTS ──────────────────────

class OpeningBalanceItem(BaseModel):
    product_id: int
    quantity: float
    remarks: Optional[str] = "Opening stock balance"

class OpeningBalanceRequest(BaseModel):
    items: List[OpeningBalanceItem]

@app.post("/api/v1/inventory/recompute-all")
def api_recompute_all_stock(
    db: Session = Depends(get_db),
    user = Depends(get_current_user)
):
    from app.models.product import Product
    from app.services.stock_service import recompute_stock
    products = db.query(Product).all()
    recomputed = []
    for p in products:
        new_qty = recompute_stock(db, p.id, p.company_id)
        recomputed.append({
            "product_id": p.id,
            "name": p.name,
            "company_id": p.company_id,
            "on_hand_qty": new_qty,
            "stock_uom": p.stock_uom or "sheet"
        })
    db.commit()
    return {"status": "success", "recomputed_count": len(recomputed), "items": recomputed}

@app.post("/api/v1/inventory/recompute/{product_id}")
def api_recompute_single_stock(
    product_id: int,
    db: Session = Depends(get_db),
    user = Depends(get_current_user)
):
    from app.models.product import Product
    from app.services.stock_service import recompute_stock
    p = db.query(Product).filter(Product.id == product_id).first()
    if not p:
        raise HTTPException(status_code=404, detail="Product not found")
    new_qty = recompute_stock(db, p.id, p.company_id)
    db.commit()
    return {"status": "success", "product_id": p.id, "on_hand_qty": new_qty}

@app.post("/api/v1/inventory/opening-balance")
def api_post_opening_balance(
    payload: OpeningBalanceRequest,
    db: Session = Depends(get_db),
    user = Depends(get_current_user)
):
    from app.models.product import Product
    from app.models.inventory import StockMovement
    from app.services.stock_service import recompute_stock
    from app.utils.helpers import get_next_code
    from datetime import datetime

    created = []
    for item in payload.items:
        p = db.query(Product).filter(Product.id == item.product_id).first()
        if not p:
            continue
        cid = user.active_company_id or p.company_id
        move_code = get_next_code(db, StockMovement, "move_number", "SM", company_id=cid)
        sm = StockMovement(
            move_number=move_code,
            product_id=p.id,
            movement_type="adjustment",
            quantity=float(item.quantity),
            reference="OPENING-BAL",
            remarks=item.remarks or "Opening stock balance",
            date=datetime.utcnow().isoformat(),
            company_id=cid,
        )
        db.add(sm)
        db.flush()
        new_qty = recompute_stock(db, p.id, cid)
        created.append({"product_id": p.id, "quantity": new_qty})

    db.commit()
    return {"status": "success", "updated_count": len(created), "items": created}


class BulkImportOpeningItem(BaseModel):
    row_number: int
    product_id: Optional[int] = None
    create_new: Optional[bool] = False
    skip: Optional[bool] = False
    product_code: Optional[str] = None
    product_name: Optional[str] = None
    brand: Optional[str] = None
    glass_type: Optional[str] = None
    thickness_mm: Optional[float] = None
    sheet_width_mm: Optional[int] = None
    sheet_height_mm: Optional[int] = None
    stock_uom: Optional[str] = "sheet"
    quantity: float
    quantity_sqm: Optional[float] = None
    quantity_sheets: Optional[float] = None
    unit_rate: Optional[float] = None
    total_value: Optional[float] = None
    rate: Optional[float] = 0.0

class BulkImportOpeningRequest(BaseModel):
    import_date: Optional[str] = None
    filename: Optional[str] = "Import.xlsx"
    warehouse_id: Optional[int] = None
    warehouse_name: Optional[str] = None
    expected_total_sqm: Optional[float] = None
    expected_total_value: Optional[float] = None
    items: List[BulkImportOpeningItem]

@app.post("/api/v1/inventory/import-opening-stock")
def api_import_opening_stock(
    payload: BulkImportOpeningRequest,
    db: Session = Depends(get_db),
    user = Depends(get_current_user)
):
    from app.models.product import Product
    from app.models.inventory import StockMovement
    from app.models.warehouse import Warehouse
    from app.services.stock_service import recompute_stock
    from app.utils.helpers import get_next_code
    from datetime import datetime

    company_id = user.active_company_id
    if not company_id:
        raise HTTPException(status_code=400, detail="Active company context is required for stock import.")

    import_date = payload.import_date or datetime.utcnow().strftime("%Y-%m-%d")
    import_timestamp = int(datetime.utcnow().timestamp())
    ref = f"OPENING-IMPORT-{import_timestamp}"

    # Resolve or create Warehouse
    target_warehouse = None
    if payload.warehouse_id:
        target_warehouse = db.query(Warehouse).filter(
            Warehouse.id == payload.warehouse_id,
            Warehouse.company_id == company_id
        ).first()

    if not target_warehouse:
        w_name = (payload.warehouse_name or "YZA Location").strip()
        target_warehouse = db.query(Warehouse).filter(
            func.lower(Warehouse.name) == w_name.lower(),
            Warehouse.company_id == company_id,
            Warehouse.is_active == True
        ).first()

        if not target_warehouse:
            target_warehouse = Warehouse(
                name=w_name,
                code="YZA",
                company_id=company_id,
                is_active=True
            )
            db.add(target_warehouse)
            db.flush()

    results = []
    imported_count = 0
    created_count = 0
    skipped_count = 0
    total_imported_sqm = 0.0
    total_imported_value = 0.0

    try:
        with db.begin_nested():
            for item in payload.items:
                q_sqm = item.quantity_sqm if item.quantity_sqm is not None else float(item.quantity or 0.0)
                q_sheets = item.quantity_sheets

                if item.skip or (q_sqm <= 0 and (q_sheets is None or q_sheets <= 0)):
                    skipped_count += 1
                    results.append({
                        "row_number": item.row_number,
                        "product_name": item.product_name or "—",
                        "status": "skipped",
                        "reason": "Marked as skip or zero/invalid quantity",
                        "product_id": item.product_id
                    })
                    continue

                target_product = None
                is_new_created = False

                # Handle Create New Product
                if item.create_new:
                    p_code = (item.product_code or "").strip()
                    p_name = (item.product_name or "").strip()
                    if not p_name:
                        raise HTTPException(status_code=400, detail=f"Row #{item.row_number}: Product Name is required to create a new product.")

                    # Check for collision in company
                    existing = None
                    if p_code:
                        existing = db.query(Product).filter(
                            Product.company_id == company_id,
                            func.lower(Product.internal_ref) == p_code.lower(),
                            Product.is_active == True
                        ).first()
                    if not existing:
                        existing = db.query(Product).filter(
                            Product.company_id == company_id,
                            func.lower(Product.name) == p_name.lower(),
                            Product.is_active == True
                        ).first()

                    if existing:
                        target_product = existing
                    else:
                        uom_val = (item.stock_uom or "sheet").lower()
                        if uom_val not in ["sheet", "nos", "service"]:
                            uom_val = "sheet"

                        if not p_code:
                            p_code = get_next_code(db, Product, "internal_ref", "PROD", company_id=company_id)

                        unit_cost = float(item.unit_rate or item.rate or 0.0)

                        target_product = Product(
                            company_id=company_id,
                            internal_ref=p_code,
                            name=p_name,
                            brand=item.brand,
                            glass_type=item.glass_type,
                            thickness_mm=item.thickness_mm,
                            sheet_width_mm=item.sheet_width_mm,
                            sheet_height_mm=item.sheet_height_mm,
                            stock_uom=uom_val,
                            cost_price=unit_cost,
                            sale_price=unit_cost,
                            product_type="storable" if uom_val != "service" else "service",
                            on_hand_qty=0.0,
                            on_hand_sqm=0.0,
                            on_hand_sheets=0.0,
                            is_active=True
                        )
                        db.add(target_product)
                        db.flush()
                        is_new_created = True
                        created_count += 1

                elif item.product_id:
                    target_product = db.query(Product).filter(
                        Product.id == item.product_id,
                        Product.company_id == company_id
                    ).first()
                    if not target_product:
                        raise HTTPException(status_code=400, detail=f"Row #{item.row_number}: Product ID {item.product_id} not found in active company.")
                else:
                    raise HTTPException(status_code=400, detail=f"Row #{item.row_number}: Neither product_id nor create_new was provided.")

                if target_product.stock_uom == "service":
                    skipped_count += 1
                    results.append({
                        "row_number": item.row_number,
                        "product_name": target_product.name,
                        "status": "skipped",
                        "reason": "Service product (non-stock)",
                        "product_id": target_product.id
                    })
                    continue

                # Update brand / cost_price if provided and missing
                if item.brand and not target_product.brand:
                    target_product.brand = item.brand
                if item.unit_rate is not None and item.unit_rate > 0 and (not target_product.cost_price or target_product.cost_price == 0):
                    target_product.cost_price = item.unit_rate

                move_code = get_next_code(db, StockMovement, "move_number", "SM", company_id=company_id)
                sm = StockMovement(
                    move_number=move_code,
                    product_id=target_product.id,
                    movement_type="adjustment",
                    quantity=q_sqm,
                    quantity_sqm=q_sqm,
                    quantity_sheets=q_sheets,
                    warehouse_id=target_warehouse.id,
                    unit_rate=item.unit_rate,
                    total_value=item.total_value,
                    reference=ref,
                    remarks=f"Tally Import ({target_warehouse.name}), Row #{item.row_number}",
                    date=import_date,
                    company_id=company_id,
                )
                db.add(sm)
                db.flush()

                new_sqm = recompute_stock(db, target_product.id, company_id)

                imported_count += 1
                total_imported_sqm += q_sqm
                if item.total_value is not None:
                    total_imported_value += item.total_value

                results.append({
                    "row_number": item.row_number,
                    "product_id": target_product.id,
                    "product_name": target_product.name,
                    "product_code": target_product.internal_ref,
                    "status": "created" if is_new_created else "imported",
                    "quantity_sqm": q_sqm,
                    "quantity_sheets": q_sheets,
                    "unit_rate": item.unit_rate,
                    "total_value": item.total_value,
                    "on_hand_sqm": new_sqm,
                    "on_hand_sheets": target_product.on_hand_sheets,
                    "reason": "Product created & opening movement posted" if is_new_created else "Opening movement posted"
                })

        db.commit()

    except Exception as e:
        db.rollback()
        if isinstance(e, HTTPException):
            raise e
        raise HTTPException(status_code=400, detail=f"Import failed during transaction. All changes rolled back. Error: {str(e)}")

    rounded_imported_sqm = round(total_imported_sqm, 4)
    rounded_imported_val = round(total_imported_value, 2)

    exp_sqm = payload.expected_total_sqm if payload.expected_total_sqm is not None else 4068.0108
    exp_val = payload.expected_total_value if payload.expected_total_value is not None else 1993017.58

    diff_sqm = round(rounded_imported_sqm - exp_sqm, 4)
    diff_val = round(rounded_imported_val - exp_val, 2)

    return {
        "status": "success",
        "reference": ref,
        "filename": payload.filename,
        "warehouse": {
            "id": target_warehouse.id,
            "name": target_warehouse.name
        },
        "summary": {
            "total_rows": len(payload.items),
            "imported": imported_count,
            "created": created_count,
            "skipped": skipped_count,
            "imported_sqm": rounded_imported_sqm,
            "imported_value": rounded_imported_val,
            "expected_sqm": exp_sqm,
            "expected_value": exp_val,
            "variance_sqm": diff_sqm,
            "variance_value": diff_val,
        },
        "results": results
    }


# ── Wholesale App Snapshot Push ───────────────────────────────────────────────

@app.post("/api/v1/wholesale-sync")
def wholesale_sync(payload: dict = Body(...), db: Session = Depends(get_db)):
    """Receive a snapshot pushed by the external wholesale app.
    Token-authenticated; no JWT. Push-only — this ERP cannot call out
    to that app because its host blocks server-to-server requests."""
    from app.models.wholesale_snapshot import WholesaleSnapshot
    expected = settings.WHOLESALE_SYNC_TOKEN
    if not expected:
        raise HTTPException(status_code=503, detail="Wholesale sync not configured")
    supplied = str(payload.get("token") or "")
    if not hmac.compare_digest(supplied, expected):
        raise HTTPException(status_code=401, detail="Invalid sync token")

    def _f(k):
        try: return float(payload.get(k) or 0)
        except (TypeError, ValueError): return 0.0
    def _i(k):
        try: return int(float(payload.get(k) or 0))
        except (TypeError, ValueError): return 0

    snap = WholesaleSnapshot(
        source=str(payload.get("source") or "essar_wholesale")[:50],
        stock_value=_f("stock_value"),   total_sheets=_i("total_sheets"),
        total_sqm=_f("total_sqm"),       total_tonnage=_f("total_tonnage"),
        total_skus=_i("total_skus"),     low_stock=_i("low_stock"),
        month_revenue=_f("month_revenue"), month_orders=_i("month_orders"),
        month_profit=_f("month_profit"), open_orders=_i("open_orders"),
        trucks_active=_i("trucks_active"),
    )
    db.add(snap)
    db.commit()
    return {"ok": True}


@app.get("/")
def root():
    return {
        "app":     settings.APP_NAME,
        "version": settings.APP_VERSION,
        "docs":    "/api/docs",
        "status":  "running",
    }

@app.get("/api/v1/health")
def health():
    return {"status": "healthy", "database": "connected"}
