"""add_hardware_labor_items_to_sales_order

Revision ID: 208bf0adcc76
Revises: 10815c21c13b
Create Date: 2026-05-26 12:01:04.985896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208bf0adcc76'
down_revision: Union[str, None] = '10815c21c13b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_orders', sa.Column('hardware_items', sa.JSON(), nullable=True))
    op.add_column('sales_orders', sa.Column('labor_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'labor_items')
    op.drop_column('sales_orders', 'hardware_items')
    # ### end Alembic commands ###
