"""add_wastage_dc_cost_totals

Revision ID: 3b08e5add59d
Revises: 8d38bfe09927
Create Date: 2026-06-05 23:11:56.183684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b08e5add59d'
down_revision: Union[str, None] = '8d38bfe09927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('wastage_items', sa.JSON(), nullable=True))
    op.add_column('quotations', sa.Column('dc_cost', sa.Float(), nullable=True))
    op.add_column('quotations', sa.Column('totals', sa.JSON(), nullable=True))
    op.add_column('sales_orders', sa.Column('wastage_items', sa.JSON(), nullable=True))
    op.add_column('sales_orders', sa.Column('dc_cost', sa.Float(), nullable=True))
    op.add_column('sales_orders', sa.Column('totals', sa.JSON(), nullable=True))
    op.add_column('sales_orders', sa.Column('processes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_orders', 'processes')
    op.drop_column('sales_orders', 'totals')
    op.drop_column('sales_orders', 'dc_cost')
    op.drop_column('sales_orders', 'wastage_items')
    op.drop_column('quotations', 'totals')
    op.drop_column('quotations', 'dc_cost')
    op.drop_column('quotations', 'wastage_items')
    # ### end Alembic commands ###
