"""add_process_master_warehouse_missing_columns

Revision ID: 89c64e1921a4
Revises: 208bf0adcc76
Create Date: 2026-05-27 16:43:48.706483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c64e1921a4'
down_revision: Union[str, None] = '208bf0adcc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_masters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('process_type', sa.String(length=50), nullable=False),
    sa.Column('charge_type', sa.String(length=30), nullable=True),
    sa.Column('rate', sa.Float(), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_process_masters_company_id'), 'process_masters', ['company_id'], unique=False)
    op.create_index(op.f('ix_process_masters_id'), 'process_masters', ['id'], unique=False)
    op.create_index(op.f('ix_process_masters_name'), 'process_masters', ['name'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_company_id'), 'warehouses', ['company_id'], unique=False)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=False)
    op.add_column('purchase_orders', sa.Column('vendor_reference', sa.String(length=200), nullable=True))
    op.add_column('quotations', sa.Column('hardware_items', sa.JSON(), nullable=True))
    op.add_column('quotations', sa.Column('labor_items', sa.JSON(), nullable=True))
    op.add_column('quotations', sa.Column('gst_mode', sa.String(length=20), nullable=True))
    op.add_column('sales_orders', sa.Column('gst_mode', sa.String(length=20), nullable=True))
    op.add_column('sales_orders', sa.Column('dc_charges', sa.Float(), nullable=True))
    op.add_column('sales_orders', sa.Column('discount_amount', sa.Float(), nullable=True))
    op.add_column('sales_orders', sa.Column('advance_received', sa.Float(), nullable=True))
    op.add_column('sales_orders', sa.Column('customer_name', sa.String(length=200), nullable=True))
    op.add_column('sales_orders', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.add_column('sales_orders', sa.Column('internal_notes', sa.Text(), nullable=True))
    op.add_column('sales_orders', sa.Column('customer_note', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'sales_orders', 'warehouses', ['warehouse_id'], ['id'])
    op.add_column('toughening_batches', sa.Column('vendor_name', sa.String(length=200), nullable=True))
    op.add_column('toughening_batches', sa.Column('wo_ids', sa.JSON(), nullable=True))
    op.add_column('toughening_batches', sa.Column('batch_date', sa.String(length=20), nullable=True))
    op.add_column('toughening_batches', sa.Column('total_pieces', sa.Integer(), nullable=True))
    op.add_column('workshop_orders', sa.Column('so_number', sa.String(length=20), nullable=True))
    op.add_column('workshop_orders', sa.Column('customer_name', sa.String(length=200), nullable=True))
    op.add_column('workshop_orders', sa.Column('jobwork_vendor', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshop_orders', 'jobwork_vendor')
    op.drop_column('workshop_orders', 'customer_name')
    op.drop_column('workshop_orders', 'so_number')
    op.drop_column('toughening_batches', 'total_pieces')
    op.drop_column('toughening_batches', 'batch_date')
    op.drop_column('toughening_batches', 'wo_ids')
    op.drop_column('toughening_batches', 'vendor_name')
    op.drop_constraint(None, 'sales_orders', type_='foreignkey')
    op.drop_column('sales_orders', 'customer_note')
    op.drop_column('sales_orders', 'internal_notes')
    op.drop_column('sales_orders', 'warehouse_id')
    op.drop_column('sales_orders', 'customer_name')
    op.drop_column('sales_orders', 'advance_received')
    op.drop_column('sales_orders', 'discount_amount')
    op.drop_column('sales_orders', 'dc_charges')
    op.drop_column('sales_orders', 'gst_mode')
    op.drop_column('quotations', 'gst_mode')
    op.drop_column('quotations', 'labor_items')
    op.drop_column('quotations', 'hardware_items')
    op.drop_column('purchase_orders', 'vendor_reference')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_company_id'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_process_masters_name'), table_name='process_masters')
    op.drop_index(op.f('ix_process_masters_id'), table_name='process_masters')
    op.drop_index(op.f('ix_process_masters_company_id'), table_name='process_masters')
    op.drop_table('process_masters')
    # ### end Alembic commands ###
