"""add_logo_to_company

Revision ID: 8d38bfe09927
Revises: f04e320147e4
Create Date: 2026-06-02 17:08:54.607133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d38bfe09927'
down_revision: Union[str, None] = 'f04e320147e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('logo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'logo')
    # ### end Alembic commands ###
